on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: 333730
          installation_id: 37515825
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Use the obtained token
        run: |
               echo " token value: " ${TOKEN}
               curl -L \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Token ${TOKEN}"\
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/orgs/orgjerome2/repos
        env:
          TOKEN: ${{ steps.generate_token.outputs.token }}
      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: orgjerome2/test2
          path: test2
      - name: Hello world action step
        id: hello
        uses: jfantou/actionGit@v1.2
