on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Obtain a GitHub App Installation Access Token
        id: githubAppAuth
        run: |
          TOKEN="$(npx obtain-github-app-installation-access-token ci eyJhcHBJZCI6IjMzMzczMCIsImluc3RhbGxhdGlvbklkIjoiMzc1MTU4MjUiLCJwcml2YXRlS2V5IjoiU0hBMjU2OnNDT1g5SUsxNDR3SDNEcVc0UjcwdGlVWWFOS29JVFNUWWgvWEpjME9zMUE9In0=)"
          echo "::add-mask::$TOKEN"
          echo "::set-output name=token::$TOKEN"
      - name: Use the obtained token
        run: |
          curl -X POST -H 'Content-Type: application/json' \
            -d '{"context":"test","state":"success"}' \
            "https://api.github.com/repos/test2/statuses/$GITHUB_SHA?access_token=$GITHUB_TOKEN"
        env:
          GITHUB_TOKEN: ${{ steps.githubAppAuth.outputs.token }}
      - name: Hello world action step
        id: hello
        uses: jfantou/actionGit@v1.2
