on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: 333730
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Use the obtained token
        run: |
               echo " token value: " $GITHUB_TOKEN
               curl -L \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer $GITHUB_TOKEN"\
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/orgs/orgjerome2/repos
        env:
          GITHUB_TOKEN: ${{ steps.githubAppAuth.outputs.token }}
      - name: Hello world action step
        id: hello
        uses: jfantou/actionGit@v1.2
