on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: 333730
          installation_id: 37515825
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Use the obtained token
        run: |
                curl -L \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer $TOKEN"\
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/app/installation-requests
        env:
          TOKEN: ${{ steps.generate_token.outputs.token }}
      - name: Hello world action step
        id: hello
        uses: jfantou/actionGit@v1.2
